### ISSUE TITLE
Logging in with incorrect username/password throws an exception

### ISSUE THREAD

**Issue by yaseenkadir** [yaseenkadir/etchedjournal#10]
1. Register a user
2. Login with an invalid password
3. See exception written in logs

```log
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:85) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:620) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:387) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.etchedjournal.etched.service.impl.KeycloakOpenIdKeycloakApi.post(KeycloakOpenIdKeycloakApi.kt:165) ~[classes/:na]
	at com.etchedjournal.etched.service.impl.KeycloakOpenIdKeycloakApi.login(KeycloakOpenIdKeycloakApi.kt:106) ~[classes/:na]
	at com.etchedjournal.etched.service.impl.AuthServiceImpl.authenticate(AuthServiceImpl.kt:158) ~[classes/:na]
	at com.etchedjournal.etched.controller.AuthServiceController.authenticate(AuthServiceController.kt:28) ~[classes/:na]
```

**Comment by yaseen95** [comment]
We can't add a unit test for this because it relies on the keycloak implementation. But we'll add one as part of [#4 adding integration tests](https://github.com/yaseen95/etchedjournal/issues/4)
